package com.f88.loanonboarding.rule;

public enum RuleCode {
    CUSTOMER_BLACKLIST_CHECK,
    CUSTOMER_AGE_CHECK,
    REQUESTED_AMOUNT_LIMIT,
    LOAN_TENURE_ALLOWED,
    LOAN_PURPOSE_ALLOWED,
    ASSET_REQUIRED,
    ASSET_DUPLICATE_CHECK,
    LTV_LIMIT_CHECK,
    LOANABLE_AMOUNT_CHECK,
    ASSET_VALUATION_DEDUCTION_LIMIT,
    LOAN_PRODUCT_PURPOSE_ALLOWED,
    LOAN_PRODUCT_ASSET_TYPE_ALLOWED,
    LOAN_PRODUCT_TENOR_ALLOWED,
    LOAN_PRODUCT_SCORE_ALLOWED,
    LOAN_PRODUCT_MIN_AMOUNT_ALLOWED
}
