spring.application.name=loan-onboarding
server.port=${SERVER_PORT:8080}

# Mặc định dùng mock profile để chạy được khi chưa có ERD/DB.
spring.profiles.default=mock

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
